name: CD Frontend (Reusable)

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      product_url:
        required: true
        type: string
      order_url:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      SIMULATE: ${{ vars.SIMULATE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Inject backend URLs into frontend/main.js
        run: |
          sed -i "s|_PRODUCT_API_URL_|${{ inputs.product_url }}|g" frontend/main.js
          sed -i "s|_ORDER_API_URL_|${{ inputs.order_url }}|g"   frontend/main.js
          echo "--- Injected main.js (first lines) ---"
          sed -n '1,40p' frontend/main.js

      - name: Azure Login
        if: ${{ env.SIMULATE != 'true' }}
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        if: ${{ env.SIMULATE != 'true' }}
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build & Push frontend
        if: ${{ env.SIMULATE != 'true' }}
        run: |
          REG="${{ secrets.ACR_LOGIN_SERVER }}"
          docker build -t "$REG/frontend:latest" frontend
          docker push "$REG/frontend:latest"

      - name: Simulated deploy summary
        if: ${{ env.SIMULATE == 'true' }}
        run: |
          echo "SIMULATION MODE: Would build/push frontend and deploy to AKS."
          echo "Using Product URL: ${{ inputs.product_url }}"
          echo "Using Order URL:   ${{ inputs.order_url }}"
